export interface GoogleReview {
  id: string;
  name: string;
  avatarText: string;
  rating: number;
  timeAgo: string;
  reviewText: string;
  isLocalGuide?: boolean;
  reviewCount?: string;
  doctorMentioned?: string;
  category?: 'Back & Neck Pain' | 'Sports & Knee Rehab' | 'Neuro & Rehabilitation' | 'Post-Surgery Rehab' | 'Home Visits' | 'General Care';
  condition?: string;
  ownerReply?: string;
  profileUrl?: string;
}

export const googleReviewsData: GoogleReview[] = [
  {
    id: 'rev-1',
    name: 'Prakash Ganesan',
    avatarText: 'PG',
    rating: 5,
    timeAgo: '2 weeks ago',
    reviewText: 'Nandhini mam and reshma sre mam very good treatment in 7 days improvement for my bells palsy treatment and Dr ashok sir speak have an great positive speech and good very good.',
    doctorMentioned: 'Dr. Ashok & Dr. Nandhini',
    category: 'Neuro & Rehabilitation',
    condition: "Bell's Palsy Treatment",
    ownerReply: "We are very happy to know that you experienced good improvement in your Bell's Palsy condition within 7 days of therapy.",
  },
  {
    id: 'rev-2',
    name: 'Giribalaji V',
    avatarText: 'GV',
    rating: 5,
    timeAgo: '21 weeks ago',
    reviewText: 'I had an ACL Grade 2 tear and visited Active Care Physio for treatment under Dr. Ashok. Within just a week, I could see remarkable recovery and improvement.',
    doctorMentioned: 'Dr. Ashok',
    category: 'Sports & Knee Rehab',
    condition: 'ACL Grade 2 Tear',
    ownerReply: "Thank you so much for your kind words and trust in Active Care Physiotherapy Centre. We're really happy to hear about your recovery.",
  },
  {
    id: 'rev-3',
    name: 'Ashok A',
    avatarText: 'AA',
    rating: 5,
    timeAgo: '21 weeks ago',
    reviewText: "We visited Active Care Center for my wife's disc-related back pain. Initially, she was struggling to walk, but after treatment she is now completely free from pain and able to return to normal active life.",
    doctorMentioned: 'Dr. Ashok',
    category: 'Back & Neck Pain',
    condition: 'Disc-Related Back Pain',
    ownerReply: 'Thank you for your valuable feedback, We are very happy to hear that you are now free from pain and back to active lifestyle.',
  },
  {
    id: 'rev-4',
    name: 'Anbu Kuppan',
    avatarText: 'AK',
    rating: 5,
    timeAgo: '34 weeks ago',
    reviewText: 'Very effective treatment, will definitely recommend their service for everyone. Dr. Ashok sir did chiropractor treatment for my back pain and the pain has reduced drastically.',
    doctorMentioned: 'Dr. Ashok',
    category: 'Back & Neck Pain',
    condition: 'Chronic Back Pain & Chiropractic',
    ownerReply: 'Thank you for your valuable feedback reviews!',
  },
  {
    id: 'rev-5',
    name: 'satheesh Kumar',
    avatarText: 'SK',
    rating: 5,
    timeAgo: '2 weeks ago',
    reviewText: 'Excellent support by Dr. Ragunath and I am feeling good in my neck pain treatment. Thanks to Active care physiotherapy centre.',
    doctorMentioned: 'Dr. Ragunath',
    category: 'Back & Neck Pain',
    condition: 'Neck Pain Treatment',
  },
  {
    id: 'rev-6',
    name: 'Vinucharan Vijayaraj',
    avatarText: 'VV',
    rating: 5,
    timeAgo: '14 weeks ago',
    reviewText: "I've had 30+ sessions for my post surgery recovery from Achilles tendon repair with Dr. Sudharshan. He is very patient, attentive, and helped me regain full mobility.",
    doctorMentioned: 'Dr. Sudharshan',
    category: 'Post-Surgery Rehab',
    condition: 'Post-Op Achilles Tendon Repair',
    ownerReply: 'Thank you for your feedback. We appreciate your trust in our rehabilitation protocols.',
  },
  {
    id: 'rev-7',
    name: 'Shakthi',
    avatarText: 'S',
    rating: 5,
    timeAgo: '19 weeks ago',
    reviewText: 'Giving physiotherapy care for a patient with GBS (Guillain-Barré Syndrome). With continuous guidance and dedicated support from Ashok sir, the patient has achieved immense recovery.',
    doctorMentioned: 'Dr. Ashok',
    category: 'Neuro & Rehabilitation',
    condition: 'GBS Neuro Rehabilitation',
    ownerReply: 'Thank you for your feedback! We are glad to see the significant neuro recovery.',
  },
  {
    id: 'rev-8',
    name: 'Irvin',
    avatarText: 'I',
    rating: 5,
    timeAgo: '15 weeks ago',
    reviewText: 'Got physiotherapy sessions at my place by Dr. Sudharshan. He is well experienced and helped me recover quickly. Highly recommended home physiotherapy service.',
    doctorMentioned: 'Dr. Sudharshan',
    category: 'Home Visits',
    condition: 'Home Physiotherapy Visit',
    ownerReply: 'Thank you for choosing our home physiotherapy service. We are pleased to provide comfort and healing at your doorstep.',
  },
  {
    id: 'rev-9',
    name: 'S Eswari',
    avatarText: 'SE',
    rating: 5,
    timeAgo: '21 weeks ago',
    reviewText: 'Very good centre for physiotherapy. I came here with severe heel pain on both legs. Dr. Ashok consulted me and gave thorough exercises. I am now completely relieved.',
    doctorMentioned: 'Dr. Ashok',
    category: 'Sports & Knee Rehab',
    condition: 'Severe Bilateral Heel Pain',
    ownerReply: "Thank you for your wonderful feedback! We're glad your heel pain has resolved.",
  },
  {
    id: 'rev-10',
    name: 'Bala Bala',
    avatarText: 'BB',
    rating: 5,
    timeAgo: '14 weeks ago',
    reviewText: 'My mother has knee pain. She took treatment here, and the pain was relieved in 10 days. Therapist Veena provided very good care and kind attention.',
    doctorMentioned: 'Dr. Veena',
    category: 'Sports & Knee Rehab',
    condition: 'Knee Pain & Mobility',
    ownerReply: 'Thank you so much for your heartfelt words. We are thrilled with your mother’s quick recovery.',
  },
  {
    id: 'rev-11',
    name: 'Linda D',
    avatarText: 'LD',
    rating: 5,
    timeAgo: '12 weeks ago',
    reviewText: 'Doctor Ragunath with great knowledge and a patient-centered approach. I had severe neck pain for the past 2 weeks. The treatment was effective, and I noticed significant improvement in my condition.',
    doctorMentioned: 'Dr. Ragunath',
    category: 'Back & Neck Pain',
    condition: 'Severe Neck Pain',
    ownerReply: 'Thank you for your valuable feedback!',
  },
  {
    id: 'rev-12',
    name: 'Aishwarya Radhaswamy',
    avatarText: 'AR',
    rating: 5,
    timeAgo: '3 weeks ago',
    reviewText: 'I had an ankle injury on my right leg. Dr. Nandini took extra care and helped me get back to my routine with tailored exercises and friendly encouragement.',
    doctorMentioned: 'Dr. Nandhini',
    category: 'Sports & Knee Rehab',
    condition: 'Ankle Injury Rehab',
    ownerReply: 'We are glad that positive guidance gave you confidence throughout your recovery.',
  },
  {
    id: 'rev-13',
    name: 'Bhuvi D',
    avatarText: 'BD',
    rating: 5,
    timeAgo: '3 weeks ago',
    reviewText: 'Reshma Doctor was a sweet, friendly and caring person. The treatment was very effective and very good service.',
    doctorMentioned: 'Dr. Reshma',
    category: 'General Care',
    condition: 'Pain Relief & Therapy',
    ownerReply: 'Thank you for your kind words! We are glad you had a positive healing experience.',
  },
  {
    id: 'rev-14',
    name: 'jenifar janesha',
    avatarText: 'JJ',
    rating: 5,
    timeAgo: '6 days ago',
    reviewText: 'Really your service is so good! The physiotherapists give well planned exercise and activities. Thank you so much for your service.',
    category: 'General Care',
    condition: 'Physiotherapy & Exercises',
  },
  {
    id: 'rev-15',
    name: 'DIWAKAR SANTHARAM',
    avatarText: 'DS',
    rating: 5,
    timeAgo: '21 weeks ago',
    reviewText: 'Very good place for physiotherapy. Owner Dr. Ashok is knowledgeable and friendly. All staff — Raghu, Veena, Nandhini are experts and very nice. Highly recommend!',
    doctorMentioned: 'Dr. Ashok, Raghu, Veena, Nandhini',
    category: 'General Care',
    condition: 'Comprehensive Physiotherapy',
    ownerReply: 'Thank you so much for your valuable feedback reviews doctor!',
  },
  {
    id: 'rev-16',
    name: 'Prince Julian',
    avatarText: 'PJ',
    rating: 5,
    timeAgo: '23 weeks ago',
    reviewText: 'I came to Active Care Physiotherapy Centre for my cervical and lumbar spondylosis with severe pain and numbness. The systematic therapy gave me tremendous relief.',
    doctorMentioned: 'Dr. Ashok & Team',
    category: 'Back & Neck Pain',
    condition: 'Cervical & Lumbar Spondylosis',
    ownerReply: 'Thank you for your valuable feedback, Mr. Prince Julian. We are very happy to hear that you are free from pain.',
  },
  {
    id: 'rev-17',
    name: 'Nivas Ranjan Bose',
    avatarText: 'NB',
    rating: 5,
    timeAgo: '51 weeks ago',
    reviewText: 'Truly grateful to Dr. Ashok for diagnosing my problem so quickly and helping me recover much faster than I expected. Best physio center in Chennai!',
    doctorMentioned: 'Dr. Ashok',
    category: 'General Care',
    condition: 'Rapid Pain Diagnosis & Relief',
    ownerReply: 'Thank you for your positive reviews!',
  },
  {
    id: 'rev-18',
    name: 'balu sundari',
    avatarText: 'BS',
    rating: 5,
    timeAgo: '40 weeks ago',
    reviewText: 'Sagaya Valli gave very good physiotherapy treatment for my wife post spinal surgery. She is very sincere and punctual in her work.',
    doctorMentioned: 'Sagaya Valli',
    category: 'Post-Surgery Rehab',
    condition: 'Post-Spine Surgery Rehabilitation',
    ownerReply: "Thank you for sharing your wonderful experience with Sagaya Valli's physiotherapy treatment!",
  },
];
